wait for lo/hi mtu
Signed-off-by: Leonard Crestez <cdleonard@gmail.com>

diff --git a/test-tcp-mtu-probing b/test-tcp-mtu-probing
--- a/test-tcp-mtu-probing
+++ b/test-tcp-mtu-probing
@@ -33,6 +33,41 @@ clean()
     fi
 }
 
+wait_loop()
+{
+    local max_iter=10
+    local sleep_interval=1
+    local cmd=("$@")
+    for ((iter = 0; iter < max_iter; ++iter)); do
+        if "${cmd[@]}"; then
+            return 0
+        fi
+        sleep "$sleep_interval"
+    done
+    return 2
+}
+
+read_last_ss_mss()
+{
+    tail -n1 "$tmpdir/watch_ss_client.log" | sed -ne "s/.* mss:\([0-9]\+\) .*/\1/pg"
+}
+
+check_mss_lo()
+{
+    local mss
+    mss=$(read_last_ss_mss)
+    echo "check mss $mss decreases to lo mtu $MTU_VALUE_LO"
+    [[ $mss -lt $MTU_VALUE_LO ]]
+}
+
+check_mss_hi()
+{
+    local mss
+    mss=$(read_last_ss_mss)
+    echo "check mss $mss increases to hi mtu $MTU_VALUE_LO"
+    [[ $mss -gt $((MTU_VALUE_HI - 100)) ]]
+}
+
 main()
 {
     # Can be set externally:
@@ -42,6 +77,8 @@ main()
     IPV4_MTU_EXPIRES=${IPV4_MTU_EXPIRES:-5}
     TCP_MTU_PROBING=${TCP_MTU_PROBING:-0}
     TCP_PROBE_INTERVAL=${TCP_MTU_PROBE_INTERVAL:-5}
+    MTU_VALUE_LO=${MTU_VALUE_LO:-3000}
+    MTU_VALUE_HI=${MTU_VALUE_HI:-9200}
 
     clean
     tmpdir=$(mktemp -d)
@@ -55,15 +92,15 @@ main()
 
     ip netns exec ns_client ip link add veth_middle type veth peer name veth_client netns ns_middle
     ip netns exec ns_client ip addr add dev veth_middle 12.0.0.1/24
-    ip netns exec ns_client ip link set veth_middle up mtu 9200
+    ip netns exec ns_client ip link set veth_middle up mtu $MTU_VALUE_HI
     ip netns exec ns_middle ip addr add dev veth_client 12.0.0.2/24
-    ip netns exec ns_middle ip link set veth_client up mtu 9200
+    ip netns exec ns_middle ip link set veth_client up mtu $MTU_VALUE_HI
 
     ip netns exec ns_server ip link add veth_middle type veth peer name veth_server netns ns_middle
     ip netns exec ns_server ip addr add dev veth_middle 23.0.0.3/24
-    ip netns exec ns_server ip link set veth_middle up mtu 9200
+    ip netns exec ns_server ip link set veth_middle up mtu $MTU_VALUE_HI
     ip netns exec ns_middle ip addr add dev veth_server 23.0.0.2/24
-    ip netns exec ns_middle ip link set veth_server up mtu 9200
+    ip netns exec ns_middle ip link set veth_server up mtu $MTU_VALUE_HI
 
     ip netns exec ns_client ip route add 23.0.0.0/24 via 12.0.0.2
     ip netns exec ns_server ip route add 12.0.0.0/24 via 23.0.0.2
@@ -117,42 +154,34 @@ main()
             &> "$tmpdir/iperf_client.log" &
     iperf_client_pid=$!
 
-    ip netns exec ns_client bash -c "while true; do ss --oneline --no-header --tcp --info | tee -a '$tmpdir/watch_ss_client.log'; sleep 0.3; done" &
+    ip netns exec ns_client bash -c "while true; do ss --oneline --no-header --tcp --info | tee -a '$tmpdir/watch_ss_client.log'; sleep 1; done" &
     watch_ss_client_pid=$!
 
-    echo "sleep 5"
-    sleep 5
-    echo "enter lo-mtu state"
-    ip netns exec ns_middle ip link set veth_server mtu 3000
-    echo "sleep 5"
-    sleep 5
-    echo "restore hi-mtu state:"
-    ip netns exec ns_middle ip link set veth_server mtu 9100
-    echo "sleep 5"
-    sleep 5
+    if wait_loop check_mss_hi; then
+        echo "ok - reached hi mss"
+    else
+        echo "not ok - failed to reach hi mss"
+        exit 1
+    fi
 
-    was_ok=0
-    max_iter=300
-    for ((iter = 0; iter < max_iter; ++iter)); do
-        items=$(tail -n1 "$tmpdir/watch_ss_client.log" | sed -ne "s/.* mss:\([0-9]\+\) pmtu:\([0-9]\+\).*/\1 \2/pg")
-        echo "item: $items"
-        if [[ -z $items ]]; then
-            echo "failed to parse watch_ss_client.log"
-            exit 2
-        fi
-        read mss pmtu < <(echo "$items")
-        echo "mss=$mss pmtu=$pmtu"
-        if [[ mss -gt 9000 ]]; then
-            echo "ok - mss back over 9000"
-            echo "sleep 5"
-            sleep 5
-            was_ok=1
-            break
-        fi
-        sleep 0.3
-    done
-    if [[ $was_ok != 1 ]]; then
-        echo "not ok - mss still under 9000"
+    echo "enter lo-mtu state"
+    ip netns exec ns_middle ip link set veth_server mtu "$MTU_VALUE_LO"
+
+    if wait_loop check_mss_lo; then
+        echo "ok - reached lo mss"
+    else
+        echo "not ok - failed to reach lo mss"
+        exit 1
+    fi
+
+    echo "restore hi-mtu state:"
+    ip netns exec ns_middle ip link set veth_server mtu "$MTU_VALUE_HI"
+    sleep 3
+
+    if wait_loop check_mss_hi; then
+        echo "ok - reached high mss"
+    else
+        echo "not ok - failed to reach high mss"
     fi
 
     clean_bgpid iperf_server_pid
